// packages/vue/src/PersianDatepicker.vue
<template>
  <div ref="container" :class="className" :style="style">
    <persian-datepicker-element
      ref="elementRef"
      :value="formattedValue"
      :placeholder="placeholder"
      :format="format"
      :show-holidays="showHolidays"
      :rtl="rtl"
      :disabled="disabled"
      :min-date="minDate"
      :max-date="maxDate"
      :disabled-dates="disabledDates"
      :holiday-types="holidayTypes"
      :range-mode="rangeMode"
      :range-start="rangeStart"
      :range-end="rangeEnd"
      @change="handleChange"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch, nextTick, computed } from 'vue';
import type { DateTuple, PersianDateChangeEvent } from 'persian-datepicker-element';

// Define props
const props = defineProps({
  modelValue: {
    type: [Array, String],
    default: undefined
  },
  placeholder: {
    type: String,
    default: ''
  },
  format: {
    type: String,
    default: 'YYYY/MM/DD'
  },
  showHolidays: {
    type: Boolean,
    default: true
  },
  rtl: {
    type: Boolean,
    default: true
  },
  disabled: {
    type: Boolean,
    default: false
  },
  minDate: {
    type: Array as () => DateTuple,
    default: undefined
  },
  maxDate: {
    type: Array as () => DateTuple,
    default: undefined
  },
  disabledDates: {
    type: String,
    default: undefined
  },
  holidayTypes: {
    type: String,
    default: undefined
  },
  className: {
    type: String,
    default: ''
  },
  style: {
    type: Object,
    default: () => ({})
  },
  // Range picker props
  rangeMode: {
    type: Boolean,
    default: false
  },
  rangeStart: {
    type: Array as () => DateTuple,
    default: undefined
  },
  rangeEnd: {
    type: Array as () => DateTuple,
    default: undefined
  }
});

// Define emits
const emit = defineEmits(['update:modelValue', 'change']);

// Define refs
const container = ref<HTMLElement | null>(null);
const elementRef = ref<HTMLElement | null>(null);

// Computed property for formatted value
const formattedValue = computed(() => {
  if (!props.modelValue) return '';
  if (Array.isArray(props.modelValue)) {
    return props.modelValue.join('/');
  }
  return String(props.modelValue);
});

// Handle date change
const handleChange = (event: CustomEvent) => {
  const detail = event.detail as PersianDateChangeEvent;
  emit('update:modelValue', detail.jalali);
  emit('change', detail);
};

// Watch for modelValue changes
watch(() => props.modelValue, (newValue) => {
  nextTick(() => {
    if (elementRef.value) {
      if (Array.isArray(newValue) && newValue.length === 3) {
        try {
          (elementRef.value as any).setValue(newValue[0], newValue[1], newValue[2]);
        } catch (error) {
          console.error('Failed to set value:', error);
        }
      } else if (typeof newValue === 'string') {
        elementRef.value.setAttribute('value', newValue);
      }
    }
  });
}, { immediate: false });

// Watch for min/max date changes
watch(() => props.minDate, (newValue) => {
  nextTick(() => {
    if (elementRef.value) {
      if (newValue) {
        elementRef.value.setAttribute('min-date', JSON.stringify(newValue));
      }
    }
  });
});

// Watch for max date changes
watch(() => props.maxDate, (newValue) => {
  nextTick(() => {
    if (elementRef.value) {
      if (newValue) {
        elementRef.value.setAttribute('max-date', JSON.stringify(newValue));
      }
    }
  });
});

// Watch for disabled dates changes
watch(() => props.disabledDates, (newValue) => {
  nextTick(() => {
    if (elementRef.value) {
      if (newValue) {
        elementRef.value.setAttribute('disabled-dates', JSON.stringify(newValue));
      } else {
        elementRef.value.removeAttribute('disabled-dates');
      }
    }
  });
});

// Watch for range mode changes
watch(() => props.rangeMode, (newValue) => {
  nextTick(() => {
    if (elementRef.value) {
      elementRef.value.setAttribute('range-mode', String(newValue));
    }
  });
});

// Watch for range start changes
watch(() => props.rangeStart, (newValue) => {
  nextTick(() => {
    if (elementRef.value) {
      if (newValue) {
        elementRef.value.setAttribute('range-start', JSON.stringify(newValue));
      }
    }
  });
});

// Watch for range end changes
watch(() => props.rangeEnd, (newValue) => {
  nextTick(() => {
    if (elementRef.value) {
      if (newValue) {
        elementRef.value.setAttribute('range-end', JSON.stringify(newValue));
      }
    }
  });
});

onMounted(() => {
  nextTick(() => {
    if (props.modelValue && elementRef.value) {
      if (Array.isArray(props.modelValue) && props.modelValue.length === 3) {
        try {
          (elementRef.value as any).setValue(props.modelValue[0], props.modelValue[1], props.modelValue[2]);
        } catch (error) {
          console.error('Failed to set initial value:', error);
        }
      } else if (typeof props.modelValue === 'string') {
        elementRef.value.setAttribute('value', props.modelValue);
      }
    }
  });
});

// Define methods to expose
defineExpose({
  getValue: () => (elementRef.value as any)?.getValue(),
  setValue: (year: number, month: number, day: number) => {
    (elementRef.value as any)?.setValue(year, month, day);
  },
  open: () => (elementRef.value as any)?.open(),
  close: () => (elementRef.value as any)?.close(),
  // Range picker methods
  setRange: (start: DateTuple, end: DateTuple) => {
    (elementRef.value as any)?.setRange(start, end);
  },
  getRange: () => {
    return (elementRef.value as any)?.getRange() || { start: null, end: null };
  },
  clear: () => {
    (elementRef.value as any)?.clear();
  }
});
</script>

<style>
/* Add any additional styles here */
</style>

// packages/react/src/PersianDatepicker.tsx
import React, { forwardRef, useRef, useEffect, useImperativeHandle, CSSProperties } from 'react';
import type { 
  PersianDatePickerElementOptions,
  PersianDateChangeEvent,
  DateTuple,
  PersianEvent
} from 'persian-datepicker-element';

// Ensure the web component is registered globally when imported
if (typeof window !== 'undefined') {
  import('persian-datepicker-element');
}

// Props interface that extends the web component options
export interface PersianDatepickerProps extends Omit<PersianDatePickerElementOptions, 'onChange'> {
  // Override onChange to use proper React event handling
  onChange?: (event: PersianDateChangeEvent) => void;
  
  // Additional React-specific props
  className?: string;
  style?: CSSProperties;
  
  // CSS custom properties as direct props for easier styling
  primaryColor?: string;
  primaryHover?: string;
  backgroundColor?: string;
  foregroundColor?: string;
  borderColor?: string;
  borderRadius?: string;
  fontFamily?: string;
  holidayColor?: string;
  holidayBg?: string;
  
  // New dark mode and scrollbar related props
  scrollbarWidth?: string;
  scrollbarThumbColor?: string;
  scrollbarThumbHoverColor?: string;
  scrollbarTrackColor?: string;
  scrollbarBorderRadius?: string;
  
  // Dark mode helper prop
  darkMode?: boolean;

  // New props for format and limits
  minDate?: DateTuple;
  maxDate?: DateTuple;
  disabledDates?: string;

  // Range picker props
  rangeMode?: boolean;
  rangeStart?: DateTuple;
  rangeEnd?: DateTuple;
}

// Methods that will be available via ref
export interface PersianDatepickerMethods {
  getValue: () => DateTuple;
  setValue: (year: number, month: number, day: number) => void;
  open: () => void;
  close: () => void;
  getElement: () => HTMLElement | null;
  // Range picker methods
  setRange: (start: DateTuple, end: DateTuple) => void;
  getRange: () => { start: DateTuple | null; end: DateTuple | null };
  clear: () => void;
}

// Define an extended HTMLElement interface with custom methods
interface PersianDatepickerElement extends HTMLElement {
  getValue?: () => DateTuple;
  setValue?: (year: number, month: number, day: number) => void;
  open?: () => void;
  close?: () => void;
  setAttribute(name: string, value: string): void;
  // Range picker methods
  setRange?: (start: DateTuple, end: DateTuple) => void;
  getRange?: () => { start: DateTuple | null; end: DateTuple | null };
  clear?: () => void;
}

// Helper to convert camelCase to kebab-case for HTML attributes
const toKebabCase = (str: string): string => {
  return str.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
};

// Convert boolean and array values to strings for HTML attributes
const convertValueToAttribute = (value: any): string => {
  if (typeof value === 'boolean') {
    return value ? 'true' : 'false';
  }
  if (Array.isArray(value)) {
    return JSON.stringify(value);
  }
  return String(value);
};

// The actual component
export const PersianDatepicker = forwardRef<PersianDatepickerMethods, PersianDatepickerProps>(
  (props, ref) => {
    const {
      value,
      onChange,
      placeholder,
      format,
      showHolidays,
      rtl,
      minDate,
      maxDate,
      disabledDates,
      disabled,
      className,
      style,
      darkMode,
      rangeMode,
      rangeStart,
      rangeEnd,
      ...rest
    } = props;

    const elementRef = useRef<PersianDatepickerElement | null>(null);
    const handleChange = useRef<((e: Event) => void) | null>(null);

    useImperativeHandle(ref, () => ({
      setValue: (year: number, month: number, day: number) => {
        elementRef.current?.setValue?.(year, month, day);
      },
      getValue: () => {
        const value = elementRef.current?.getValue?.();
        return value || [1400, 1, 1] as DateTuple;
      },
      open: () => {
        elementRef.current?.open?.();
      },
      close: () => {
        elementRef.current?.close?.();
      },
      getElement: () => elementRef.current,
      // Range picker methods
      setRange: (start: DateTuple, end: DateTuple) => {
        elementRef.current?.setRange?.(start, end);
      },
      getRange: () => {
        return elementRef.current?.getRange?.() || { start: null, end: null };
      },
      clear: () => {
        elementRef.current?.clear?.();
      }
    }));

    // Create the event handler
    useEffect(() => {
      if (onChange) {
        handleChange.current = (e: Event) => {
          const customEvent = e as CustomEvent<PersianDateChangeEvent>;
          onChange(customEvent.detail);
        };
      }
    }, [onChange]);

    // Add/remove event listener
    useEffect(() => {
      const element = elementRef.current;
      const handler = handleChange.current;

      if (element && handler) {
        element.addEventListener('change', handler);
        return () => {
          element.removeEventListener('change', handler);
        };
      }
    }, []);

    // Convert DateTuple to string for attributes
    const convertDateTupleToString = (date: DateTuple | undefined): string => {
      if (!date) return '';
      return JSON.stringify(date);
    };

    useEffect(() => {
      if (elementRef.current) {
        if (value) elementRef.current.setAttribute('value', Array.isArray(value) ? value.join('/') : String(value));
        if (placeholder) elementRef.current.setAttribute('placeholder', placeholder);
        if (format) elementRef.current.setAttribute('format', format);
        if (showHolidays !== undefined) elementRef.current.setAttribute('show-holidays', String(showHolidays));
        if (rtl !== undefined) elementRef.current.setAttribute('rtl', String(rtl));
        if (minDate) elementRef.current.setAttribute('min-date', convertDateTupleToString(minDate));
        if (maxDate) elementRef.current.setAttribute('max-date', convertDateTupleToString(maxDate));
        if (disabledDates) elementRef.current.setAttribute('disabled-dates', disabledDates);
        if (disabled !== undefined) elementRef.current.setAttribute('disabled', String(disabled));
        // Range picker attributes
        if (rangeMode !== undefined) elementRef.current.setAttribute('range-mode', String(rangeMode));
        if (rangeStart) elementRef.current.setAttribute('range-start', convertDateTupleToString(rangeStart));
        if (rangeEnd) elementRef.current.setAttribute('range-end', convertDateTupleToString(rangeEnd));
      }
    }, [value, placeholder, format, showHolidays, rtl, minDate, maxDate, disabledDates, disabled, rangeMode, rangeStart, rangeEnd]);

    const minDateStr = convertDateTupleToString(minDate);
    const maxDateStr = convertDateTupleToString(maxDate);
    const rangeStartStr = convertDateTupleToString(rangeStart);
    const rangeEndStr = convertDateTupleToString(rangeEnd);

    const elementProps = {
      value,
      placeholder,
      format,
      'show-holidays': showHolidays,
      rtl,
      'min-date': minDateStr,
      'max-date': maxDateStr,
      'disabled-dates': disabledDates,
      disabled,
      'range-mode': rangeMode,
      'range-start': rangeStartStr,
      'range-end': rangeEndStr,
      ...rest
    } as React.HTMLAttributes<HTMLElement>;

    return (
      <div className={className} style={style}>
        <persian-datepicker-element
          ref={elementRef}
          {...elementProps}
        />
      </div>
    );
  }
);

// Add custom element declaration
declare global {
  namespace JSX {
    interface IntrinsicElements {
      'persian-datepicker-element': React.DetailedHTMLProps<React.HTMLAttributes<HTMLElement> & {
        value?: string;
        placeholder?: string;
        format?: string;
        'show-holidays'?: boolean;
        rtl?: boolean;
        'min-date'?: string;
        'max-date'?: string;
        'disabled-dates'?: string;
        disabled?: boolean;
        'range-mode'?: boolean;
        'range-start'?: string;
        'range-end'?: string;
      }, HTMLElement>;
    }
  }
}
