// output/angular/persian-date-picker.component.ts
import { Component, Input, Output, EventEmitter, ViewChild, ElementRef, AfterViewInit, OnChanges, SimpleChanges, OnDestroy, NgModule } from '@angular/core';

// Import the web component
import '@shadnext/';

/**
 * PersianDatePicker - An Angular component version of the  web component
 * 
 * This component was generated using the shadnext CLI.
 * It provides the same functionality as the original web component but with an Angular API.
 */
@Component({
  selector: 'app-persian-date-picker',
  templateUrl: './persian-date-picker.component.html',
  styleUrls: ['./persian-date-picker.component.scss'],
})
export class PersianDatePickerComponent implements AfterViewInit, OnChanges, OnDestroy {
  /** Selected date value */
  @Input() value: string | null = null;
  
  /** Placeholder text for the input */
  @Input() placeholder: string = 'انتخاب تاریخ';
  
  /** Primary color for the component */
  @Input() primaryColor: string = '#3b82f6';
  
  /** Whether to use right-to-left layout */
  @Input() rtl: boolean = true;
  
  /** Theme for the component */
  @Input() theme: 'light' | 'dark' = 'light';
  
  /** CSS class to apply to the component */
  @Input() className: string = '';
  
  /** Event emitted when a date is selected */
  @Output() dateSelected = new EventEmitter<string>();
  
  /**
   * Reference to the web component element
   */
  @ViewChild('persianDatepicker') persianDatepickerRef!: ElementRef;
  
  /**
   * Event handler function reference for cleanup
   */
  private dateSelectedHandler: ((e: Event) => void) | null = null;
  
  /**
   * After the view is initialized, set up the web component
   */
  ngAfterViewInit(): void {
    this.setupWebComponent();
  }
  
  /**
   * When inputs change, update the web component
   */
  ngOnChanges(changes: SimpleChanges): void {
    if (!this.persianDatepickerRef?.nativeElement) return;
    
    const element = this.persianDatepickerRef.nativeElement;
    
    if (changes['value'] && this.value) {
      element.setAttribute('date', this.value);
    }
    
    if (changes['placeholder']) {
      element.setAttribute('placeholder', this.placeholder);
    }
    
    if (changes['theme']) {
      element.setAttribute('theme', this.theme);
    }
  }
  
  /**
   * Clean up event listeners when the component is destroyed
   */
  ngOnDestroy(): void {
    this.removeEventListeners();
  }
  
  /**
   * Set up the web component and add event listeners
   */
  private setupWebComponent(): void {
    const element = this.persianDatepickerRef.nativeElement;
    
    // Set initial properties
    if (this.value) element.setAttribute('date', this.value);
    element.setAttribute('placeholder', this.placeholder);
    element.setAttribute('theme', this.theme);
    
    // Add event listener
    this.dateSelectedHandler = (e: Event) => {
      const customEvent = e as CustomEvent;
      this.value = customEvent.detail;
      this.dateSelected.emit(customEvent.detail);
    };
    
    element.addEventListener('dateSelected', this.dateSelectedHandler);
  }
  
  /**
   * Remove event listeners
   */
  private removeEventListeners(): void {
    const element = this.persianDatepickerRef?.nativeElement;
    if (element && this.dateSelectedHandler) {
      element.removeEventListener('dateSelected', this.dateSelectedHandler);
      this.dateSelectedHandler = null;
    }
  }
}

/**
 * Module for the PersianDatePicker component
 */
@NgModule({
  declarations: [PersianDatePickerComponent],
  imports: [],
  exports: [PersianDatePickerComponent],
})
export class PersianDatePickerModule {}

// test-angular/output/react/PersianDatePicker.tsx
import React, { useState, useEffect, useRef } from 'react';
import { Container, WebComponentWrapper } from './PersianDatePicker.styles';

// Import the web component
import '@shadnext/persian-datepicker-element';

/**
 * PersianDatePicker - A React component version of the persian-datepicker-element web component
 * 
 * This component was generated using the shadnext CLI.
 * It provides the same functionality as the original web component but with a React API.
 * This version uses styled-components for styling.
 */

interface PersianDatePickerProps {
  value?: string;
  onChange?: (date: string) => void;
  placeholder?: string;
  rtl?: boolean;
  primaryColor?: string;
  theme?: 'light' | 'dark';
  className?: string;
  [key: string]: any;
}

export const PersianDatePicker: React.FC<PersianDatePickerProps> = ({
  value,
  onChange,
  placeholder = 'انتخاب تاریخ',
  rtl = true,
  primaryColor = '#3b82f6',
  theme = 'light',
  className = '',
  ...props
}) => {
  // State
  const [selectedDate, setSelectedDate] = useState<string | null>(value || null);
  const elementRef = useRef<HTMLElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  
  // Initialize web component
  useEffect(() => {
    const element = elementRef.current;
    if (!element) return;

    // Set initial properties
    if (value) element.setAttribute('date', value);
    if (placeholder) element.setAttribute('placeholder', placeholder);
    element.setAttribute('theme', theme);
    
    // Add event listener
    const handleDateSelected = (e: Event) => {
      const customEvent = e as CustomEvent;
      setSelectedDate(customEvent.detail);
      if (onChange) onChange(customEvent.detail);
    };

    element.addEventListener('dateSelected', handleDateSelected);
    
    return () => {
      element.removeEventListener('dateSelected', handleDateSelected);
    };
  }, [value, placeholder, theme, onChange]);
  
  return (
    <Container 
      ref={containerRef} 
      rtl={rtl} 
      primaryColor={primaryColor}
      theme={theme}
      className={className} 
      {...props}
    >
      <WebComponentWrapper>
        <shadnext-persian-datepicker 
          ref={elementRef as React.RefObject<HTMLElement>}
        />
      </WebComponentWrapper>
    </Container>
  );
};
